[package]
name = "black_hole_renderer"
version = "0.1.0"

[dependencies]
csv = "*"
serde = { version = "*", features = ["derive"] }
image = "0.23.3"
rayon = "*"
indicatif = {version = "*", features = ["with_rayon"]}